local map = vim.keymap.set
map({ "n", "i", "v" }, "<C-s>", "<Cmd>write<CR><Esc>", { desc = "Guardar archivo" })
map("n", "<leader>w", "<Cmd>write<CR>", { desc = "Guardar" })
map("n", "<leader>q", "<Cmd>confirm quit<CR>", { desc = "Cerrar ventana" })
map("n", "<Esc>", "<Cmd>nohlsearch<CR>", { desc = "Limpiar búsqueda" })
map("n", "<C-a>", "ggVG", { desc = "Seleccionar todo" })
map("n", "<C-z>", "u", { desc = "Deshacer" })
map("i", "<C-z>", "<C-o>u", { desc = "Deshacer" })
map("n", "<C-y>", "<C-r>", { desc = "Rehacer" })
map("x", "<leader>y", '"+y', { desc = "Copiar al portapapeles" })
map("x", "<leader>X", '"+d', { desc = "Cortar al portapapeles" })
map({ "n", "x" }, "<leader>p", '"+p', { desc = "Pegar del portapapeles" })
map("x", "<C-c>", '"+y', { desc = "Copiar al portapapeles" })
map("x", "<C-x>", '"+d', { desc = "Cortar al portapapeles" })
for key, direction in pairs({ h = "h", j = "j", k = "k", l = "l" }) do
  map("n", "<C-" .. key .. ">", "<C-w>" .. direction, { desc = "Mover a ventana " .. direction })
end
map("n", "<leader>,", "<C-w>h", { desc = "Ventana izquierda" })
map("n", "<leader>.", "<C-w>l", { desc = "Ventana derecha" })
map("n", "<leader>bd", "<Cmd>bdelete<CR>", { desc = "Cerrar buffer" })
map("n", "<leader>bn", "<Cmd>enew<CR>", { desc = "Nuevo buffer" })
map("n", "<leader>tt", function()
  require("config.tasks").terminal()
end, { desc = "Terminal" })
map("t", "<Esc><Esc>", [[<C-\><C-n>]], { desc = "Modo normal en terminal" })
map("n", "<leader>cm", function()
  require("config.tasks").make()
end, { desc = "Make del proyecto" })
map("n", "<leader>cv", function()
  require("config.tasks").verilog()
end, { desc = "Simular Verilog/SV" })
map("n", "<leader>ch", function()
  require("config.tasks").vhdl()
end, { desc = "Simular VHDL" })
map("n", "<leader>cw", function()
  require("config.tasks").waves()
end, { desc = "Abrir ondas" })
